# Generated by Django 5.0.7 on 2024-07-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Food_Name', models.CharField(max_length=30, null=True, verbose_name='Yemek Adı')),
                ('Food_Price', models.PositiveIntegerField(null=True, verbose_name='Yemek Fiyatı')),
                ('Food_Recipe', models.TextField(max_length=1000, null=True, verbose_name='Yemek Tarifi')),
                ('Food_Image', models.ImageField(default='menu/default.jpeg', upload_to='menu/%Y/%m/%d/', verbose_name='Yemek Resmi')),
                ('Food_Available', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
        ),
    ]
