# Generated by Django 5.0.7 on 2024-07-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=40)),
                ('image', models.ImageField(default='comments/default.jpeg', upload_to='comments/%Y/%m/%d/', verbose_name='Müşteri Resmi')),
                ('active', models.BooleanField(default=False)),
                ('message', models.TextField(max_length=300)),
            ],
        ),
    ]
