# Generated by Django 5.0.7 on 2024-07-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0010_alter_comment_email_alter_comment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, default='comments/default.jpg', null=True, upload_to='comments/%Y/%m/%d/', verbose_name='Müşteri Resmi'),
        ),
    ]
