# Generated by Django 5.0.7 on 2024-07-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='hour',
            field=models.CharField(default='9.00', max_length=5),
        ),
    ]
