# Generated by Django 5.0.7 on 2024-07-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_reservation_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='Date',
            field=models.DateField(null=True),
        ),
    ]
