# Generated by Django 5.0.7 on 2024-07-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_reservation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='person',
            field=models.IntegerField(max_length=2, null=True),
        ),
    ]
