# Generated by Django 5.0.7 on 2024-07-18 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_reservationquery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReservationQuery',
        ),
    ]
